version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: sandro
      POSTGRES_PASSWORD: Data@123
      POSTGRES_DB: shopping_cart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shopping_cart_network

  redis:
    image: redis
    container_name: redis_container
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - shopping_cart_network

networks:
  shopping_cart_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
